apiVersion: apps/v1
kind: Deployment
metadata:
  name: comentarios-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comentarios-api
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
      labels:
        app: comentarios-api
    spec:
      containers:
        - name: comentarios-api
          image: felipejoseph/comentarios-api:{{tag}}
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: comentarios-api-service
spec:
  selector:
    app: comentarios-api
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
