apiVersion: apps/v1
kind: Deployment
metadata:
  name: comentarios-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:  
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"        
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: felipejoseph/comentarios-api:{{tag}}
          ports: 
          - containerPort: 8080
          env: 
          - name: MONGODB_URI
            value: mongodb://mongouser:mongopwd@mongodb-service:27017/admin
--- 
apiVersion: v1
kind: Service
metadata:
  name: comentarios-api
spec:
  selector:
    app: comentarios-api
  ports:
    - port: 80
      targetPort: 8080   
      nodePort: 30001   
  type: LoadBalancer
